#ifndef CYGONCE_PKGCONF_HAL_ARM_LPC2XXX_H
#define CYGONCE_PKGCONF_HAL_ARM_LPC2XXX_H
/*
 * File <pkgconf/hal_arm_lpc2xxx.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGBLD_HAL_VAR_INTS_H <cyg/hal/hal_var_ints.h>
#define CYGHWR_HAL_ARM_LPC2XXX LPC210x
#define CYGHWR_HAL_ARM_LPC2XXX_LPC210x
#define CYGHWR_HAL_ARM_LPC2XXX_FAMILY LPC210X
#define CYGHWR_HAL_ARM_LPC2XXX_FAMILY_LPC210X
#define CYGHWR_HAL_ARM_LPC2XXX_VARIANT_VERSION 1
#define CYGHWR_HAL_ARM_LPC2XXX_VARIANT_VERSION_1
#define CYGHWR_HAL_ARM_LPC2XXX_SUFFIX no_suffix
#define CYGHWR_HAL_ARM_LPC2XXX_SUFFIX_no_suffix
#define CYGNUM_HAL_ARM_VECTOR_0x14 0xB4405F62
#define CYGNUM_HAL_ARM_VECTOR_0x14_0xB4405F62
#define CYGNUM_HAL_ARM_LPC2XXX_VPBDIV 4
#define CYGNUM_HAL_ARM_LPC2XXX_VPBDIV_4
#define CYGNUM_HAL_ARM_LPC2XXX_PCLK 14745600
#define CYGNUM_HAL_ARM_LPC2XXX_PCLK_14745600
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 589824
#define CYGNUM_HAL_RTC_PERIOD_589824
#define CYGHWR_HAL_ARM_LPC2XXX_EXTINT_ERRATA 1
#define CYGHWR_HAL_ARM_LPC2XXX_IDLE_PWRSAVE 1
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY 0
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY_0
#define CYGINT_HAL_ARM_LPC2XXX_IAP_CALL 1
#define CYGINT_HAL_ARM_LPC2XXX_IAP_CALL_1
#define CYGBLD_BUILD_HAL_LPC2XXX_WITH_IAP_CALL 1
#define CYGNUM_HAL_ARM_LPC2XXX_IAP_CALL_SAFE 1

#endif
