#ifndef CYGONCE_PKGCONF_HAL_ARM_LPC2XXX_OLPCE2294_H
#define CYGONCE_PKGCONF_HAL_ARM_LPC2XXX_OLPCE2294_H
/*
 * File <pkgconf/hal_arm_lpc2xxx_olpce2294.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "ARM7TDMI-S"
#define HAL_PLATFORM_BOARD  "Olimex LPC-E2294 development board"
#define HAL_PLATFORM_EXTRA  ""
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_38400
#define CYGNUM_HAL_ARM_LPC2XXX_XTAL_FREQ 14745600
#define CYGNUM_HAL_ARM_LPC2XXX_XTAL_FREQ_14745600
#define CYGNUM_HAL_ARM_LPC2XXX_PLL_MUL 4
#define CYGNUM_HAL_ARM_LPC2XXX_PLL_MUL_4
#define CYGNUM_HAL_ARM_LPC2XXX_CLOCK_SPEED 58982400
#define CYGNUM_HAL_ARM_LPC2XXX_CLOCK_SPEED_58982400
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
