/*
 * Automatically generated C config: don't edit
 * Dist builder
 * Fri Dec 11 00:06:46 2009
 */
#define AUTOCONF_INCLUDED
#define CONFIG_USER_BUSYBOX_FEATURE_IFCONFIG_STATUS 1
#define CONFIG_USER_RAMIMAGE_RAMFS64 1
#define CONFIG_USER_BUSYBOX_INCLUDE_SUSv2 1
#define CONFIG_USER_BUSYBOX_TELNETD 1
#define CONFIG_USER_BUSYBOX_INSTALL_APPLET_SYMLINKS 1
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#define CONFIG_USER_BUSYBOX_PING 1
#define CONFIG_USER_BUSYBOX_MONOTONIC_SYSCALL 1
#define CONFIG_DISTVERSION "4.0"
#define CONFIG_USER_BUSYBOX_MD5_SIZE_VS_SPEED 2
#define CONFIG_USER_BUSYBOX_BUSYBOX_EXEC_PATH "/proc/self/exe"
#define CONFIG_USER_INIT_INIT 1
#define CONFIG_USER_BUSYBOX_TRUE 1
#define CONFIG_USER_BUSYBOX_TEST 1
#define CONFIG_USER_BUSYBOX_FEATURE_DEVPTS 1
#define CONFIG_USER_BUSYBOX_IFCONFIG 1
#define CONFIG_USER_BUSYBOX_FEATURE_INETD_SUPPORT_BUILTIN_CHARGEN 1
#define CONFIG_USER_BUSYBOX_FEATURE_INETD_SUPPORT_BUILTIN_DISCARD 1
#define CONFIG_USER_BUSYBOX_FEATURE_SYSLOG 1
#define CONFIG_USER_BUSYBOX_FEATURE_INETD_SUPPORT_BUILTIN_DAYTIME 1
#define CONFIG_USER_BUSYBOX_GETOPT_LONG 1
#define CONFIG_USER_BUSYBOX_FEATURE_FANCY_PING 1
#define CONFIG_USER_BUSYBOX_FALSE 1
#define CONFIG_USER_BUSYBOX_FEATURE_INETD_SUPPORT_BUILTIN_ECHO 1
#define CONFIG_USER_BUSYBOX_FEATURE_COPYBUF_KB 4
#define CONFIG_USER_BUSYBOX_INETD 1
#define CONFIG_USER_BUSYBOX_FEATURE_INETD_SUPPORT_BUILTIN_TIME 1
#define CONFIG_USER_BUSYBOX_HAVE_DOT_CONFIG 1
#define CONFIG_USER_BUSYBOX_NOMMU 1
#define CONFIG_USER_BUSYBOX_ROUTE 1
#define CONFIG_USER_BUSYBOX_FEATURE_SH_IS_NONE 1
#define CONFIG_USER_BUSYBOX_PASSWORD_MINLEN 6
#define CONFIG_USER_BUSYBOX_NO_DEBUG_LIB 1
#define CONFIG_USER_FB_TEST 1
#define CONFIG_USER_SASH_SH 1
#define CONFIG_USER_SASH_PS 1
#define CONFIG_USER_BUSYBOX_FEATURE_IFCONFIG_HW 1
#define CONFIG_USER_BUSYBOX_FEATURE_TELNETD_STANDALONE 1
#define CONFIG_USER_BUSYBOX_STATIC 1
#define CONFIG_USER_INIT_EXPAND 1
#define CONFIG_USER_BUSYBOX_PREFIX "./_install"
#define CONFIG_USER_BUSYBOX_IOCTL_HEX2STR_ERROR 1
